apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vector
  - kube-prometheus-stack
  - grafana
  - thanos
  - services
  - blackbox-exporter
  - rittal-exporter
  - certspotter
  - login-exporter
  - alertmanager-hookshot-adapter